service: storyin-serverless1
frameworkVersion: "4.1.11"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  api:
    handler: index.handler
    name: storyin-handler1
    events:
      - httpApi: "*"
